<?php
echo '';
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<!--';
echo 'Metro City Template';
echo 'http://www.templatemo.com/tm-470-metro-city';
echo '-->';
echo '<meta charset="utf-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<title>Metro City - About</title>';
echo '<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' rel='stylesheet' type='text/css'>';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="css/font-awesome.min.css" rel="stylesheet">';
echo '<link href="css/templatemo-style.css" rel="stylesheet">';
echo '';
echo '<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->';
echo '<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->';
echo '<!--[if lt IE 9]>';
echo '<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>';
echo '<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>';
echo '<![endif]-->';
echo '';
echo '</head>';
echo '<body class="about">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-header">';
echo '<a href="index.html" class="tm-site-name">Metro City</a>';
echo '<div class="mobile-menu-icon">';
echo '<i class="fa fa-bars"></i>';
echo '</div>';
echo '<nav class="tm-nav">';
echo '<ul>';
echo '<li><a href="index.html">Home</a></li>';
echo '<li><a href="about.html" class="active">About</a></li>';
echo '<li><a href="features.html">Features</a></li>';
echo '<li><a href="contact.html">Contact</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="tm-banner tm-bn-2">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-banner-text">';
echo '<div class="tm-banner-text-inner">';
echo '<h1 class="tm-banner-title">Creative Design Agency</h1>';
echo '<p class="tm-banner-description">Lorem Ipsum Proin Gravida</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-about-left tm-about-lr tm-white-box">';
echo '<article class="tm-about-text">';
echo '<header class="text-uppercase">';
echo '<h2 class="tm-h2">Lorem Ipsum Nam Telus Odion</h2>';
echo '<h3 class="tm-red-text">Elit Class Himese Juso</h3>';
echo '</header>';
echo '<div class="tm-intro-description tm-gray-text">';
echo '<p class="tm-about-text-block"><span class="tm-blue-text">Metro City</span> is free responsive layout from <span class="tm-blue-text">templatemo</span>. Nam nec tellus a odio tincidunt auctor a ornare odio. Sed non mauris vitae erat consequat auctor eu in elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris in erat justo. Nullam ac urna eu felis dapibu.</p>';
echo '<p class="tm-about-text-block">Rcondimentum sit amet a augue. Sed non neque elit. Sed ut imperdiet nisi. Prion condimentum fermentum nunc. Etiam pharetra.</p>';
echo '<ul class="tm-red-circle-check tm-about-text-block">';
echo '<li><i class="fa fa-check-circle tm-check"></i> Aenean sollicitudin lorem quis</li>';
echo '<li><i class="fa fa-check-circle tm-check"></i> Duis sed odio sit amet</li>';
echo '<li><i class="fa fa-check-circle tm-check"></i> Morbi accumsan ipsum velit.</li>';
echo '<li><i class="fa fa-check-circle tm-check"></i> Nam nec tellus a odio</li>';
echo '<li><i class="fa fa-check-circle tm-check"></i> Sed non mauris vitae erat consequat</li>';
echo '</ul>';
echo '<a href="#" class="tm-button tm-red-button tm-about-text-block">Read More</a>';
echo '</div>';
echo '</article>';
echo '</div>';
echo '<div class="tm-about-right tm-about-lr">';
echo '<img src="img/about-1.jpg" alt="Image" class="tm-about-img">';
echo '<div class="tm-2-columns">';
echo '<div class="tm-about-container tm-position-relative tm-light-gray-box">';
echo '<h2 class="tm-h2 tm-about-title">What <span class="tm-blue-text">We Do</span></h2>';
echo '<p class="tm-gray-text">Morbi accumsan ipsum velit dam nec tellus a odio tincidunt auctor a ornare odio.</p>';
echo '<a href="#"><i class="fa fa-3x fa-angle-down tm-blue-text"></i></a>';
echo '</div>';
echo '<div>';
echo '<img src="img/about-2.jpg" alt="image" class="tm-about-img-2">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="tm-about-left">';
echo '<div class="tm-video-box">';
echo '<div class="tm-video-box-overlay">';
echo '<p class="tm-video-description"><span class="tm-red-text">Video</span><br>Recondiment</p>';
echo '<a href="#" class="tm-play absolute-center tm-flex-center">';
echo '<i class="fa fa-4x fa-play-circle tm-red-button-alpha"></i>';
echo '</a>';
echo '</div>';
echo '<img src="img/about-3.jpg" alt="Image" class="tm-video-img">';
echo '</div>';
echo '</div>';
echo '<div class="tm-about-right">';
echo '<div class="tm-2-columns">';
echo '<div>';
echo '<img src="img/about-4.jpg" alt="image" class="tm-about-img-4">';
echo '</div>';
echo '<div class="tm-about-container tm-position-relative tm-light-gray-box">';
echo '<h2 class="tm-h2 tm-intro-title">Our <span class="tm-blue-text">Services</span></h2>';
echo '<p class="tm-gray-text">Morbi accumsan ipsum velit dam nec tellus a odio tincidunt auctor a ornare odio.</p>';
echo '<a href="#"><i class="fa fa-3x fa-angle-down tm-blue-text"></i></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="tm-block-2-container">';
echo '<div class="tm-block-2 tm-block-order-2">';
echo '<div class="tm-footer-block tm-blue-box tm-footer-text-container">';
echo '<h3 class="tm-footer-text-title">Design With Happiness</h3>';
echo '<p class="tm-footer-text-description">Lorem Ipsum Proin Gravida</p>';
echo '</div>';
echo '</div>';
echo '<div class="tm-block-2 tm-block-order-1">';
echo '<p class="tm-footer-block tm-copyright-text">';
echo 'Copyright &copy; 2084 Metro City';
echo '| Design: <a rel="nofollow" href="http://www.templatemo.com/tm-470-metro-city" target="_parent">Metro City</a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>      <!-- jQuery -->';
echo '<script type="text/javascript" src="js/templatemo-script.js"></script>      <!-- Templatemo Script -->';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>