<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<!--';
echo 'Metro City Template';
echo 'http://www.templatemo.com/tm-470-metro-city';
echo '-->';
echo '<meta charset="utf-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<title>Metro City - Contact</title>';
echo '<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' rel='stylesheet' type='text/css'>';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="css/font-awesome.min.css" rel="stylesheet">';
echo '<link href="css/templatemo-style.css" rel="stylesheet">';
echo '';
echo '<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->';
echo '<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->';
echo '<!--[if lt IE 9]>';
echo '<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>';
echo '<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>';
echo '<![endif]-->';
echo '';
echo '</head>';
echo '<body class="contact">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-header">';
echo '<a href="index.html" class="tm-site-name">Metro City</a>';
echo '<div class="mobile-menu-icon">';
echo '<i class="fa fa-bars"></i>';
echo '</div>';
echo '<nav class="tm-nav">';
echo '<ul>';
echo '<li><a href="index.html">Home</a></li>';
echo '<li><a href="about.html">About</a></li>';
echo '<li><a href="features.html">Features</a></li>';
echo '<li><a href="contact.html" class="active">Contact</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="tm-banner tm-bn-4">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-banner-text">';
echo '<div class="tm-banner-text-inner">';
echo '<h1 class="tm-banner-title">Creative Design Agency</h1>';
echo '<p class="tm-banner-description">Lorem Ipsum Proin Gravida</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-contact-lr">';
echo '<div class="tm-map-container">';
echo '<div id="google-map"></div>';
echo '</div>';
echo '<div class="tm-2-columns">';
echo '<div class="col-lg-push-6 col-md-push-6 col-sm-push-6 col-xs-push-6 tm-contact-small-box tm-about-container tm-position-relative tm-white-box">';
echo '<h2 class="tm-h2 tm-about-title">Follow Us On <span class="tm-red-text margin-top-15">Social Networks</span></h2>';
echo '</div>';
echo '<div class="col-lg-pull-6 col-md-pull-6 col-sm-pull-6 col-xs-pull-6 tm-contact-small-box tm-red-box">';
echo '<i class="fa fa-4x fa-caret-left tm-triangle-left"></i>';
echo '<div class="tm-contact-social-icons">';
echo '<a href="#" class="tm-contact-social-icon"><i class="fa fa-twitter"></i></a>';
echo '<a href="#" class="tm-contact-social-icon"><i class="fa fa-rss"></i></a>';
echo '<a href="#" class="tm-contact-social-icon"><i class="fa fa-facebook"></i></a>';
echo '<a href="#" class="tm-contact-social-icon"><i class="fa fa-google-plus"></i></a>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '<div class="tm-contact-lr">';
echo '<div class="tm-2-columns">';
echo '<div class="tm-contact-small-box tm-about-container tm-position-relative tm-white-box">';
echo '<h2 class="tm-h2 margin-bottom-0"><i class="fa fa-map-marker"></i> Our <span class="tm-blue-text">Address</span></h2>';
echo '</div>';
echo '<div class="tm-contact-small-box">';
echo '<i class="fa fa-4x fa-caret-right tm-triangle-right"></i>';
echo '<p class="tm-address">123, Rama IX Road,<br>Bangkok 12345,<br>Thailand.</p>';
echo '<img src="img/contact.jpg" alt="image" class="tm-contact-address-img">';
echo '</div>';
echo '</div>';
echo '<div class="tm-contact-form-container">';
echo '<form action="#" method="post" class="tm-contact-form">';
echo '<h2 class="tm-h2 tm-white-text">Contact <span class="tm-blue-text">Form</span></h2>';
echo '<div class="form-group margin-top-30">';
echo '<input type="text" id="contact_name" class="form-control" placeholder="NAME" />';
echo '</div>';
echo '<div class="form-group">';
echo '<input type="email" id="contact_email" class="form-control" placeholder="EMAIL" />';
echo '</div>';
echo '<div class="form-group">';
echo '<input type="text" id="contact_subject" class="form-control" placeholder="SUBJECT" />';
echo '</div>';
echo '<div class="form-group">';
echo '<textarea id="contact_message" class="form-control" rows="6" placeholder="MESSAGE"></textarea>';
echo '</div>';
echo '<div class="form-group">';
echo '<button class="tm-blue-button tm-form-submit-button" type="submit" name="submit">Send</button>';
echo '</div>';
echo '</form>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="tm-block-2-container">';
echo '<div class="tm-block-2 tm-block-order-2">';
echo '<div class="tm-footer-block tm-blue-box tm-footer-text-container">';
echo '<h3 class="tm-footer-text-title">Design With Happiness</h3>';
echo '<p class="tm-footer-text-description">Lorem Ipsum Proin Gravida</p>';
echo '</div>';
echo '</div>';
echo '<div class="tm-block-2 tm-block-order-1">';
echo '<p class="tm-footer-block tm-copyright-text">';
echo 'Copyright &copy; 2084 Metro City';
echo '| Design: <a rel="nofollow" href="http://www.templatemo.com/tm-470-metro-city" target="_parent">Metro City</a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>      <!-- jQuery -->';
echo '<script type="text/javascript" src="js/templatemo-script.js"></script>      <!-- Templatemo Script -->';
echo '<script>';
echo '/* Google map';
echo '------------------------------------------------*/';
echo 'var map = '';';
echo 'var center;';
echo '';
echo 'function initialize() {';
echo 'var mapOptions = {';
echo 'zoom: 16,';
echo 'center: new google.maps.LatLng(13.758468,100.567481),';
echo 'scrollwheel: false,';
echo 'draggable:false';
echo '};';
echo '';
echo 'map = new google.maps.Map(document.getElementById('google-map'),  mapOptions);';
echo '';
echo 'google.maps.event.addDomListener(map, 'idle', function() {';
echo 'calculateCenter();';
echo '});';
echo '';
echo 'google.maps.event.addDomListener(window, 'resize', function() {';
echo 'map.setCenter(center);';
echo '});';
echo '}';
echo '';
echo 'function calculateCenter() {';
echo 'center = map.getCenter();';
echo '}';
echo '';
echo 'function loadGoogleMap(){';
echo 'var script = document.createElement('script');';
echo 'script.type = 'text/javascript';';
echo 'script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&' + 'callback=initialize';';
echo 'document.body.appendChild(script);';
echo '}';
echo '$(document).ready(function(){';
echo 'loadGoogleMap();';
echo '});';
echo '</script>';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>