<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<!--';
echo 'Metro City Template';
echo 'http://www.templatemo.com/tm-470-metro-city';
echo '-->';
echo '<meta charset="utf-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<title>Metro City - Features</title>';
echo '<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' rel='stylesheet' type='text/css'>';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="css/font-awesome.min.css" rel="stylesheet">';
echo '<link href="css/templatemo-style.css" rel="stylesheet">';
echo '';
echo '<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->';
echo '<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->';
echo '<!--[if lt IE 9]>';
echo '<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>';
echo '<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>';
echo '<![endif]-->';
echo '';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-header">';
echo '<a href="index.html" class="tm-site-name">Metro City</a>';
echo '<div class="mobile-menu-icon">';
echo '<i class="fa fa-bars"></i>';
echo '</div>';
echo '<nav class="tm-nav">';
echo '<ul>';
echo '<li><a href="index.html">Home</a></li>';
echo '<li><a href="about.html">About</a></li>';
echo '<li><a href="features.html" class="active">Features</a></li>';
echo '<li><a href="contact.html">Contact</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="tm-banner tm-bn-3">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-banner-text">';
echo '<div class="tm-banner-text-inner">';
echo '<h1 class="tm-banner-title">Creative Design Agency</h1>';
echo '<p class="tm-banner-description">Lorem Ipsum Proin Gravida</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="boxes-container">';
echo '<div class="boxes-left">';
echo '<div class="box">';
echo '<div class="tm-block-1 tm-text-block content">';
echo '<h2 class="tm-h2">Duis Sedio Sitam Elit Class</h2>';
echo '<p class="text-justify tm-gray-text">Nam nec risus feugiat dui ultrices dignissim. Morbi ex purus, commodo a tristique eu, mollis a nisi. Pellentesque in enim sit amet tellus ornare fringilla eget eu arcu.</p>';
echo '</div>';
echo '</div>';
echo '<div class="box">';
echo '<img src="img/features-1.jpg" alt="Features" class="tm-block-1 content">';
echo '</div>';
echo '<div class="box">';
echo '<a href="#" class="content">';
echo '<div class="tm-block-1 tm-text-block tm-blue-box">';
echo '<i class="fa fa-align-left fa-3x"></i>';
echo '<h3 class="text-uppercase">Latest News</h3>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="box">';
echo '<div class="tm-block-1 tm-text-block content">';
echo '<h2 class="tm-h2">Velit Prion Nigh Alitquet Isum</h2>';
echo '<p class="text-justify tm-gray-text">Ut tempor, tellus nec euismod laoreet, risus risus porttitor arcu, egestas tempus quam purus sed velit. Aenean sed nulla et mi ornare semper. Cras nec gravida augue.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="boxes-right">';
echo '<div class="box col-lg-push-6 col-md-push-6 col-sm-push-6 col-xs-push-6">';
echo '<img src="img/features-2.jpg" alt="Features" class="tm-block-1 content">';
echo '</div>';
echo '<div class="box col-lg-pull-6 col-md-pull-6 col-sm-pull-6 col-xs-pull-6">';
echo '<div class="tm-block-1 tm-text-block content">';
echo '<h2 class="tm-h2">Bendum Actor Aenean Soli</h2>';
echo '<p class="text-justify tm-gray-text"><span class="tm-blue-text">Metro City</span> is free HTML5 layout from <span class="tm-blue-text">templatemo</span>. You can use this template for any website without giving any credit link back. Nulla gravida orci augue, egestas vestibulum.</p>';
echo '</div>';
echo '</div>';
echo '<div class="box">';
echo '<a href="#" class="content">';
echo '<div class="tm-block-1 tm-text-block tm-red-box">';
echo '<i class="fa fa-comments-o fa-3x"></i>';
echo '<h3 class="text-uppercase">Testimonials</h3>';
echo '</div>';
echo '</a>';
echo '</div>';
echo '<div class="box">';
echo '<div class="tm-block-1 tm-text-block content">';
echo '<h2 class="tm-h2">Consequat Ipsu Dinquis Bid</h2>';
echo '<p class="text-justify tm-gray-text">In et quam id libero venenatis venenatis. Morbi vitae justo vulputate, auctor augue eu, pulvinar augue. Vestibulum placerat sem eu posuere laoreet.</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="tm-block-2-container">';
echo '<div class="tm-block-2 tm-block-order-2">';
echo '<a href="#">';
echo '<img src="img/features-4.jpg" alt="Features" class="img-responsive width-100-p">';
echo '</a>';
echo '<div class="tm-footer-block tm-blue-box tm-footer-text-container">';
echo '<h3 class="tm-footer-text-title">Design With Happiness</h3>';
echo '<p class="tm-footer-text-description">Lorem Ipsum Proin Gravida</p>';
echo '</div>';
echo '</div>';
echo '<div class="tm-block-2 tm-block-order-1">';
echo '<a href="#">';
echo '<div class="tm-position-relative">';
echo '<img src="img/features-3.jpg" alt="Features" class="img-responsive width-100-p">';
echo '<div class="tm-block-2-text">';
echo '<p><span class="margin-right-20"><i class="fa fa-heart"></i> 72</span><i class="fa fa-comment"></i> 68</p>';
echo '<p class="text-uppercase">By Candy Walk</p>';
echo '</div>';
echo '</div>';
echo '</a>';
echo '<p class="tm-footer-block tm-copyright-text">';
echo 'Copyright &copy; 2084 Metro City';
echo '| Design: <a rel="nofollow" href="http://www.templatemo.com/tm-470-metro-city" target="_parent">Metro City</a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>      <!-- jQuery -->';
echo '<script type="text/javascript" src="js/templatemo-script.js"></script>      <!-- Templatemo Script -->';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>