<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<!--';
echo 'Metro City Template';
echo 'http://www.templatemo.com/tm-470-metro-city';
echo '-->';
echo '<meta charset="utf-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
echo '<title>Metro City - templatemo</title>';
echo '<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,400italic,600,700' rel='stylesheet' type='text/css'>';
echo '<link href="css/bootstrap.min.css" rel="stylesheet">';
echo '<link href="css/font-awesome.min.css" rel="stylesheet">';
echo '<link href="css/templatemo-style.css" rel="stylesheet">';
echo '';
echo '<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->';
echo '<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->';
echo '<!--[if lt IE 9]>';
echo '<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>';
echo '<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>';
echo '<![endif]-->';
echo '';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-header">';
echo '<a href="index.html" class="tm-site-name">Metro City</a>';
echo '<div class="mobile-menu-icon">';
echo '<i class="fa fa-bars"></i>';
echo '</div>';
echo '<nav class="tm-nav">';
echo '<ul>';
echo '<li><a href="index.html" class="active">Home</a></li>';
echo '<li><a href="about.html">About</a></li>';
echo '<li><a href="features.html">Features</a></li>';
echo '<li><a href="contact.html">Contact</a></li>';
echo '</ul>';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="tm-banner tm-bn-1">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-banner-text">';
echo '<div class="tm-banner-text-inner">';
echo '<h1 class="tm-banner-title">Creative Design Agency</h1>';
echo '<p class="tm-banner-description">Lorem Ipsum Proin Gravida</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="tm-blocks-container">';
echo '<div class="tm-home-left">';
echo '<div class="tm-2-columns">';
echo '<div class="tm-home-block-small tm-img-text tm-position-relative tm-white-box">';
echo '<div class="tm-social-icons-container">';
echo '<a href="#"><i class="tm-social-icon fa fa-facebook"></i></a>';
echo '<a href="#"><i class="tm-social-icon fa fa-twitter"></i></a>';
echo '<a href="#"><i class="tm-social-icon fa fa-rss"></i></a>';
echo '<a href="#"><i class="tm-social-icon fa fa-google-plus"></i></a>';
echo '</div>';
echo '<h2 class="tm-h2">Duis Sedio Sitam Elit Class</h2>';
echo '<p class="text-justify tm-gray-text">Morbi accumsan ipsum velamso nec tellus roin ...</p>';
echo '</div>';
echo '<div class="tm-home-block-small tm-position-relative">';
echo '<i class="fa fa-4x fa-caret-right tm-triangle-right"></i>';
echo '<img src="img/home-1.jpg" alt="image" class="tm-home-img-1">';
echo '</div>';
echo '</div>';
echo '<div class="tm-home-block-big tm-position-relative">';
echo '<div class="tm-red-box tm-img-overlay tm-img-overlay-1">';
echo '<p>Ribendum elit conseqt ipsum sagittis nibh</p>';
echo '</div>';
echo '<img src="img/home-3.jpg" alt="image" class="img-responsive">';
echo '</div>';
echo '<div class="tm-2-columns">';
echo '<div class="tm-home-block-small tm-img-text tm-position-relative tm-white-box">';
echo '<div class="tm-social-icons-container">';
echo '<a href="#"><i class="tm-social-icon fa fa-facebook"></i></a>';
echo '<a href="#"><i class="tm-social-icon fa fa-twitter"></i></a>';
echo '<a href="#"><i class="tm-social-icon fa fa-rss"></i></a>';
echo '<a href="#"><i class="tm-social-icon fa fa-google-plus"></i></a>';
echo '</div>';
echo '<h2 class="tm-h2">Lorem Ipsum Do Elit Class</h2>';
echo '<p>By: David Hanson</p>';
echo '</div>';
echo '<div class="tm-home-block-small tm-position-relative">';
echo '<img src="img/home-5.jpg" alt="image" class="tm-home-img-1">';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="tm-home-right">';
echo '<div class="tm-home-block-big tm-position-relative tm-home-img-big-2-container">';
echo '<div class="tm-blue-box tm-img-overlay tm-img-overlay-2">';
echo '<p>Ribendum elit conseqt ipsum sagittis nibh</p>';
echo '</div>';
echo '<img src="img/home-2.jpg" alt="image" class="img-responsive">';
echo '</div>';
echo '<div class="tm-home-block-big tm-2-columns-tall">';
echo '<div class="col tm-intro-container tm-position-relative tm-white-box">';
echo '<div class="tm-social-icons-container">';
echo '<a href="#"><i class="tm-social-icon fa fa-facebook"></i></a>';
echo '<a href="#"><i class="tm-social-icon fa fa-twitter"></i></a>';
echo '<a href="#"><i class="tm-social-icon fa fa-rss"></i></a>';
echo '<a href="#"><i class="tm-social-icon fa fa-google-plus"></i></a>';
echo '</div>';
echo '<h2 class="tm-h2 tm-intro-title">Lorem Ipsum Elit Conseaut Odiosi</h2>';
echo '<p class="tm-gray-text tm-intro-description">This is free responsive layout from <span class="tm-blue-text">templatemo</span>. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit consequat ipsum, nec sagittis sem nibh id elit. Duis odio sit amet nibh vulputate cursus.</p>';
echo '<a href="#" class="tm-button tm-blue-button margin-top-30">Learn More</a>';
echo '</div>';
echo '<div class="col tm-2-rows tm-2-rows-2">';
echo '<div class="tm-home-block-small tm-home-img-1-container">';
echo '<img src="img/home-4.jpg" alt="image" class="tm-home-img-1">';
echo '</div>';
echo '<div class="tm-home-block-small padding-30 tm-dark-box tm-dark-box-img-text">';
echo '<h2 class="tm-h2 tm-dark-gray-text">Lorem Ipsumdol Elit Class</h2>';
echo '<a href="#" class="tm-button tm-blue-button margin-top-15">Learn More</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="tm-block-2-container">';
echo '';
echo '<div class="tm-block-2 tm-block-order-2">';
echo '<div class="tm-footer-block tm-blue-box tm-footer-text-container">';
echo '<h3 class="tm-footer-text-title">Design With Happiness</h3>';
echo '<p class="tm-footer-text-description">Lorem Ipsum Proin Gravida</p>';
echo '</div>';
echo '</div>';
echo '<div class="tm-block-2 tm-block-order-1">';
echo '<p class="tm-footer-block tm-copyright-text">';
echo 'Copyright &copy; 2084 Metro City';
echo '| Design: <a rel="nofollow" href="http://www.templatemo.com/tm-470-metro-city" target="_parent">Metro City</a>';
echo '</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '';
echo '<script type="text/javascript" src="js/jquery-1.11.2.min.js"></script>      <!-- jQuery -->';
echo '<script type="text/javascript" src="js/templatemo-script.js"></script>      <!-- Templatemo Script -->';
echo '';
echo '</body>';
echo '</html>';
echo '';
?>